# frozen_string_literal: true

# Setting initial data
User.create([{ username: 'Mark', email: 'mark@gmail.com', password: 'mark123', bio: 'I am dentist and love travelling',
               account: 'Public', image: File.open(Rails.public_path.join('seeds/image11.jpeg')) },
             { username: 'Jessica', email: 'jessica@gmail.com', password: 'jessica123',
               bio: 'I am a studnet and interested in learning new skills', account: 'Private',
               image: File.open(Rails.public_path.join('seeds/image18.jpeg')) },
             { username: 'Noah', email: 'noah@yahoo.com', password: 'noah123', bio: 'Interested in history',
               account: 'Public', image: File.open(Rails.public_path.join('seeds/image22.jpeg')) },
             { username: 'Robert', email: 'robert@gmail.com', password: 'robert123', bio: 'Creating a life, I love',
               account: 'Private', image: File.open(Rails.public_path.join('seeds/image1.jpeg')) },
             { username: 'Katherine', email: 'katherine@yahoo.com', password: 'kat123',
               bio: 'Captivated from life, showing it here', account: 'Public',
               image: File.open(Rails.public_path.join('seeds/image13.jpeg')) }])
Post.create([{ description: 'Turn your dreams into reality', user_id: 1 },
             { description: 'You cannot become the best without first being the worst', user_id: 1 },
             { description: 'Life is what happens to you', user_id: 2 },
             { description: 'Saying YES to the new adventures', user_id: 3 },
             { description: 'Leave sparkles whereever you go', user_id: 3 },
             { description: 'Turn dreams into visions and visions into reality', user_id: 4 },
             { description: 'You are out there hustling to claim what is yours', user_id: 5 }])
Story.create([{ content: 'Follow me to the greatness', user_id: 1 }, { content: 'I am on my journey', user_id: 2 },
              { content: 'My story will inspire you', user_id: 3 }, { content: 'Witness the history', user_id: 4 },
              { content: 'Having the time of my life', user_id: 5 }])
Photo.create([{ photoable_type: 'Post', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image1.jpeg')) },
              { photoable_type: 'Post', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image2.jpeg')) },
              { photoable_type: 'Post', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image3.jpeg')) },
              { photoable_type: 'Post', photoable_id: 2,
                image: File.open(Rails.public_path.join('seeds/image4.jpeg')) },
              { photoable_type: 'Post', photoable_id: 2,
                image: File.open(Rails.public_path.join('seeds/image5.jpeg')) },
              { photoable_type: 'Post', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image6.jpeg')) },
              { photoable_type: 'Post', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image7.jpeg')) },
              { photoable_type: 'Post', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image8.jpeg')) },
              { photoable_type: 'Post', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image9.jpeg')) },
              { photoable_type: 'Post', photoable_id: 4,
                image: File.open(Rails.public_path.join('seeds/image10.jpeg')) },
              { photoable_type: 'Post', photoable_id: 5,
                image: File.open(Rails.public_path.join('seeds/image11.jpeg')) },
              { photoable_type: 'Post', photoable_id: 5,
                image: File.open(Rails.public_path.join('seeds/image12.jpeg')) },
              { photoable_type: 'Post', photoable_id: 6,
                image: File.open(Rails.public_path.join('seeds/image13.jpeg')) },
              { photoable_type: 'Post', photoable_id: 6,
                image: File.open(Rails.public_path.join('seeds/image4.jpeg')) },
              { photoable_type: 'Post', photoable_id: 6,
                image: File.open(Rails.public_path.join('seeds/image15.jpeg')) },
              { photoable_type: 'Post', photoable_id: 7,
                image: File.open(Rails.public_path.join('seeds/image16.jpeg')) },
              { photoable_type: 'Post', photoable_id: 7,
                image: File.open(Rails.public_path.join('seeds/image6.jpeg')) },
              { photoable_type: 'Story', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image18.jpeg')) },
              { photoable_type: 'Story', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image19.jpeg')) },
              { photoable_type: 'Story', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image20.jpeg')) },
              { photoable_type: 'Story', photoable_id: 1,
                image: File.open(Rails.public_path.join('seeds/image21.jpeg')) },
              { photoable_type: 'Story', photoable_id: 2,
                image: File.open(Rails.public_path.join('seeds/image22.jpeg')) },
              { photoable_type: 'Story', photoable_id: 2,
                image: File.open(Rails.public_path.join('seeds/image23.jpeg')) },
              { photoable_type: 'Story', photoable_id: 2,
                image: File.open(Rails.public_path.join('seeds/image13.jpeg')) },
              { photoable_type: 'Story', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image8.jpeg')) },
              { photoable_type: 'Story', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image1.jpeg')) },
              { photoable_type: 'Story', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image2.jpeg')) },
              { photoable_type: 'Story', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image3.jpeg')) },
              { photoable_type: 'Story', photoable_id: 3,
                image: File.open(Rails.public_path.join('seeds/image4.jpeg')) },
              { photoable_type: 'Story', photoable_id: 4,
                image: File.open(Rails.public_path.join('seeds/image5.jpeg')) },
              { photoable_type: 'Story', photoable_id: 4,
                image: File.open(Rails.public_path.join('seeds/image6.jpeg')) },
              { photoable_type: 'Story', photoable_id: 5,
                image: File.open(Rails.public_path.join('seeds/image7.jpeg')) },
              { photoable_type: 'Story', photoable_id: 5,
                image: File.open(Rails.public_path.join('seeds/image8.jpeg')) },
              { photoable_type: 'Story', photoable_id: 5,
                image: File.open(Rails.public_path.join('seeds/image9.jpeg')) }])
Like.create([{ post_id: 1, user_id: 2 }, { post_id: 1, user_id: 5 }, { post_id: 1, user_id: 4 },
             { post_id: 2, user_id: 4 }, { post_id: 2, user_id: 5 }, { post_id: 2, user_id: 1 },
             { post_id: 3, user_id: 4 }, { post_id: 3, user_id: 3 },
             { post_id: 4, user_id: 1 }, { post_id: 4, user_id: 2 }, { post_id: 4, user_id: 3 },
             { post_id: 5, user_id: 2 }, { post_id: 5, user_id: 3 },
             { post_id: 6, user_id: 5 }, { post_id: 6, user_id: 1 },
             { post_id: 7, user_id: 3 }, { post_id: 7, user_id: 4 }])
Comment.create([{ statement: 'Insightful indeed', post_id: 1, user_id: 4 },
                { statement: 'Have a great weekend', post_id: 1, user_id: 2 },
                { statement: 'Your posting skills are good', post_id: 1, user_id: 5 },
                { statement: 'Thats really motivating', post_id: 2, user_id: 2 },
                { statement: 'Keep posting', post_id: 2, user_id: 5 },
                { statement: 'I doubt it', post_id: 3, user_id: 1 },
                { statement: 'Thats your decision', post_id: 3, user_id: 2 },
                { statement: 'This has inspired me to do better', post_id: 3, user_id: 4 },
                { statement: 'The great adventures are waiting', post_id: 4, user_id: 1 },
                { statement: 'Everybody should explore', post_id: 4, user_id: 2 },
                { statement: 'What do you guys think of it', post_id: 5, user_id: 3 },
                { statement: 'What goes around comes around', post_id: 5, user_id: 1 },
                { statement: 'Agreed', post_id: 6, user_id: 1 }, { statement: 'Thats right', post_id: 6, user_id: 5 },
                { statement: 'Dreams are real', post_id: 6, user_id: 3 },
                { statement: 'Follow your dreams', post_id: 6, user_id: 2 },
                { statement: 'Hard work is key', post_id: 7, user_id: 3 },
                { statement: 'Get what you want', post_id: 7, user_id: 4 }])
Relationship.create([{ follower_id: 2, followed_id: 1 }, { follower_id: 5, followed_id: 1 },
                     { follower_id: 4, followed_id: 1 },
                     { follower_id: 1, followed_id: 2 }, { follower_id: 4, followed_id: 2 },
                     { follower_id: 3, followed_id: 2 },
                     { follower_id: 1, followed_id: 3 }, { follower_id: 2, followed_id: 3 },
                     { follower_id: 1, followed_id: 4 }, { follower_id: 2, followed_id: 4 },
                     { follower_id: 3, followed_id: 4 }, { follower_id: 5, followed_id: 4 },
                     { follower_id: 3, followed_id: 5 }, { follower_id: 4, followed_id: 5 }])
